# Generated by Django 3.2.9 on 2021-12-01 18:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('directory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.directorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('content', models.FileField(upload_to='')),
                ('checksum', models.CharField(max_length=64, null=True)),
                ('last_changed', models.DateTimeField(default=datetime.datetime(2021, 12, 1, 18, 48, 8, 394359, tzinfo=utc))),
                ('isPublic', models.BooleanField(default=False)),
                ('directory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.directorymodel')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUIDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
