# Generated by Django 3.2.9 on 2021-11-26 16:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.directorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(blank=True, default='', upload_to='')),
                ('size', models.IntegerField()),
                ('sizeUnit', models.CharField(default='KB', max_length=5)),
                ('checksum', models.CharField(max_length=64)),
                ('last_changed', models.DateTimeField(default=datetime.datetime(2021, 11, 26, 17, 51, 12, 29148))),
                ('isPublic', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=1000)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.directorymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
