# Generated by Django 3.2.9 on 2021-11-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
