# Generated by Django 3.2.9 on 2021-11-26 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211126_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='last_changed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 19, 7, 54, 459612)),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
