# Generated by Django 3.2.9 on 2021-11-26 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211126_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='filemodel',
            name='size',
        ),
        migrations.RemoveField(
            model_name='filemodel',
            name='sizeUnit',
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='last_changed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 19, 12, 20, 122463)),
        ),
    ]
