# Generated by Django 3.2.9 on 2021-11-26 18:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0004_auto_20211126_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='checksum',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.directorymodel'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='filename',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='last_changed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 19, 13, 58, 867549)),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
