# Generated by Django 3.2.9 on 2021-11-26 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20211126_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='last_changed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 19, 17, 36, 244716)),
        ),
    ]
