# Generated by Django 3.2.9 on 2021-11-27 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_filemodel_last_changed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='filename',
            new_name='content',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='last_changed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 12, 28, 37, 909815)),
        ),
    ]
