# Generated by Django 3.2.9 on 2021-11-27 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20211127_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='last_changed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 12, 4, 30, 80614, tzinfo=utc)),
        ),
    ]
