# Generated by Django 3.2.9 on 2021-11-27 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_filemodel_last_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='location',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='last_changed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 13, 48, 41, 144001, tzinfo=utc)),
        ),
    ]
