# Generated by Django 3.2.9 on 2021-11-27 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20211127_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='last_changed',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 13, 51, 31, 973013, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
