# Generated by Django 3.2.9 on 2021-12-01 10:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20211127_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='content',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='last_changed',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 10, 12, 22, 414950, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='location',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
